name: Java CI with Maven

on:
  push:
    branches: [ main ]      # Run on push to main
  pull_request:
    branches: [ main ]      # Also run on PR to main

jobs:
  build:
    runs-on: ubuntu-latest   # Use latest Ubuntu VM

    steps:
    - name: Checkout code
      uses: actions/checkout@v4   # Pull your GitHub repo files

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'   # OpenJDK from Adoptium
        java-version: '17'        # Use Java 17

    - name: Compile the code
      run: mvn compile            # Compile with Maven

    - name: Run unit tests
      run: mvn test               # Run your unit tests
